name: inquire-docs

services:
  chroma:
    image: chromadb/chroma
    env_file: .env
    ports:
      - "8000:8000"
    restart: always

  pgvector:
    image: pgvector/pgvector:pg16
    env_file: .env
    ports:
     - "5432:5432"
    restart: always

  backend:
    build:
      context: .
    pull_policy: build
    depends_on:
      - chroma
      - pgvector
