version: '3.1'

services:

  db_pg_vector:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
